/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gatebuzz.oxfordapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * A mapping of filters available per endpoints.
 */
public class FiltersResults   {
  @SerializedName("entries")
  private String[] entries = null;

  @SerializedName("inflections")
  private String[] inflections = null;

  @SerializedName("translations")
  private String[] translations = null;

  @SerializedName("wordlist")
  private String[] wordlist = null;

  public FiltersResults entries(String[] entries) {
    this.entries = entries;
    return this;
  }

   /**
   * A list of filters available for Retrieve Entry endpoint
   * @return entries
  **/
  public String[] getEntries() {
    return entries;
  }

  public void setEntries(String[] entries) {
    this.entries = entries;
  }

  public FiltersResults inflections(String[] inflections) {
    this.inflections = inflections;
    return this;
  }

   /**
   * A list of filters available for LEMMATRON endpoint
   * @return inflections
  **/
  public String[] getInflections() {
    return inflections;
  }

  public void setInflections(String[] inflections) {
    this.inflections = inflections;
  }

  public FiltersResults translations(String[] translations) {
    this.translations = translations;
    return this;
  }

   /**
   * A list of filters available for Translations endpoint
   * @return translations
  **/
  public String[] getTranslations() {
    return translations;
  }

  public void setTranslations(String[] translations) {
    this.translations = translations;
  }

  public FiltersResults wordlist(String[] wordlist) {
    this.wordlist = wordlist;
    return this;
  }

   /**
   * A list of filters available for Translations endpoint
   * @return wordlist
  **/
  public String[] getWordlist() {
    return wordlist;
  }

  public void setWordlist(String[] wordlist) {
    this.wordlist = wordlist;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FiltersResults filtersResults = (FiltersResults) o;
    return Objects.equals(this.entries, filtersResults.entries) &&
        Objects.equals(this.inflections, filtersResults.inflections) &&
        Objects.equals(this.translations, filtersResults.translations) &&
        Objects.equals(this.wordlist, filtersResults.wordlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, inflections, translations, wordlist);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FiltersResults {\n");
    
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    inflections: ").append(toIndentedString(inflections)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    wordlist: ").append(toIndentedString(wordlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

