/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gatebuzz.oxfordapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * A grouping of pronunciation information
 */
public class PronunciationsListInner   {
  @SerializedName("audioFile")
  private String audioFile = null;

  @SerializedName("dialects")
  private String[] dialects = null;

  @SerializedName("phoneticNotation")
  private String phoneticNotation = null;

  @SerializedName("phoneticSpelling")
  private String phoneticSpelling = null;

  @SerializedName("regions")
  private String[] regions = null;

  public PronunciationsListInner audioFile(String audioFile) {
    this.audioFile = audioFile;
    return this;
  }

   /**
   * The URL of the sound file
   * @return audioFile
  **/
  public String getAudioFile() {
    return audioFile;
  }

  public void setAudioFile(String audioFile) {
    this.audioFile = audioFile;
  }

  public PronunciationsListInner dialects(String[] dialects) {
    this.dialects = dialects;
    return this;
  }

   /**
   * A local or regional variation where the pronunciation occurs, e.g. 'British English'
   * @return dialects
  **/
  public String[] getDialects() {
    return dialects;
  }

  public void setDialects(String[] dialects) {
    this.dialects = dialects;
  }

  public PronunciationsListInner phoneticNotation(String phoneticNotation) {
    this.phoneticNotation = phoneticNotation;
    return this;
  }

   /**
   * The alphabetic system used to display the phonetic spelling
   * @return phoneticNotation
  **/
  public String getPhoneticNotation() {
    return phoneticNotation;
  }

  public void setPhoneticNotation(String phoneticNotation) {
    this.phoneticNotation = phoneticNotation;
  }

  public PronunciationsListInner phoneticSpelling(String phoneticSpelling) {
    this.phoneticSpelling = phoneticSpelling;
    return this;
  }

   /**
   * Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
   * @return phoneticSpelling
  **/
  public String getPhoneticSpelling() {
    return phoneticSpelling;
  }

  public void setPhoneticSpelling(String phoneticSpelling) {
    this.phoneticSpelling = phoneticSpelling;
  }

  public PronunciationsListInner regions(String[] regions) {
    this.regions = regions;
    return this;
  }

   /**
   * A particular area in which the pronunciation occurs, e.g. 'Great Britain'
   * @return regions
  **/
  public String[] getRegions() {
    return regions;
  }

  public void setRegions(String[] regions) {
    this.regions = regions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PronunciationsListInner pronunciationsListInner = (PronunciationsListInner) o;
    return Objects.equals(this.audioFile, pronunciationsListInner.audioFile) &&
        Objects.equals(this.dialects, pronunciationsListInner.dialects) &&
        Objects.equals(this.phoneticNotation, pronunciationsListInner.phoneticNotation) &&
        Objects.equals(this.phoneticSpelling, pronunciationsListInner.phoneticSpelling) &&
        Objects.equals(this.regions, pronunciationsListInner.regions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioFile, dialects, phoneticNotation, phoneticSpelling, regions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PronunciationsListInner {\n");
    
    sb.append("    audioFile: ").append(toIndentedString(audioFile)).append("\n");
    sb.append("    dialects: ").append(toIndentedString(dialects)).append("\n");
    sb.append("    phoneticNotation: ").append(toIndentedString(phoneticNotation)).append("\n");
    sb.append("    phoneticSpelling: ").append(toIndentedString(phoneticSpelling)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

