/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gatebuzz.oxfordapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * Description of an entry for a particular part of speech
 */
public class SentencesLexicalEntry   {
  @SerializedName("grammaticalFeatures")
  private GrammaticalFeaturesList grammaticalFeatures = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("lexicalCategory")
  private String lexicalCategory = null;

  @SerializedName("sentences")
  private ExamplesList sentences = null;

  @SerializedName("text")
  private String text = null;

  public SentencesLexicalEntry grammaticalFeatures(GrammaticalFeaturesList grammaticalFeatures) {
    this.grammaticalFeatures = grammaticalFeatures;
    return this;
  }

   /**
   * Get grammaticalFeatures
   * @return grammaticalFeatures
  **/
  public GrammaticalFeaturesList getGrammaticalFeatures() {
    return grammaticalFeatures;
  }

  public void setGrammaticalFeatures(GrammaticalFeaturesList grammaticalFeatures) {
    this.grammaticalFeatures = grammaticalFeatures;
  }

  public SentencesLexicalEntry language(String language) {
    this.language = language;
    return this;
  }

   /**
   * IANA language code
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public SentencesLexicalEntry lexicalCategory(String lexicalCategory) {
    this.lexicalCategory = lexicalCategory;
    return this;
  }

   /**
   * A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
   * @return lexicalCategory
  **/
  public String getLexicalCategory() {
    return lexicalCategory;
  }

  public void setLexicalCategory(String lexicalCategory) {
    this.lexicalCategory = lexicalCategory;
  }

  public SentencesLexicalEntry sentences(ExamplesList sentences) {
    this.sentences = sentences;
    return this;
  }

   /**
   * A list of examples of use sentences
   * @return sentences
  **/
  public ExamplesList getSentences() {
    return sentences;
  }

  public void setSentences(ExamplesList sentences) {
    this.sentences = sentences;
  }

  public SentencesLexicalEntry text(String text) {
    this.text = text;
    return this;
  }

   /**
   * A given written or spoken realisation of a an entry.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentencesLexicalEntry sentencesLexicalEntry = (SentencesLexicalEntry) o;
    return Objects.equals(this.grammaticalFeatures, sentencesLexicalEntry.grammaticalFeatures) &&
        Objects.equals(this.language, sentencesLexicalEntry.language) &&
        Objects.equals(this.lexicalCategory, sentencesLexicalEntry.lexicalCategory) &&
        Objects.equals(this.sentences, sentencesLexicalEntry.sentences) &&
        Objects.equals(this.text, sentencesLexicalEntry.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grammaticalFeatures, language, lexicalCategory, sentences, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentencesLexicalEntry {\n");
    
    sb.append("    grammaticalFeatures: ").append(toIndentedString(grammaticalFeatures)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lexicalCategory: ").append(toIndentedString(lexicalCategory)).append("\n");
    sb.append("    sentences: ").append(toIndentedString(sentences)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

