/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gatebuzz.oxfordapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * ThesaurusEntry
 */
public class ThesaurusEntry   {
  @SerializedName("homographNumber")
  private String homographNumber = null;

  @SerializedName("senses")
  private List<ThesaurusSense> senses = new ArrayList<ThesaurusSense>();

  @SerializedName("variantForms")
  private VariantFormsList variantForms = null;

  public ThesaurusEntry homographNumber(String homographNumber) {
    this.homographNumber = homographNumber;
    return this;
  }

   /**
   * Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
   * @return homographNumber
  **/
  public String getHomographNumber() {
    return homographNumber;
  }

  public void setHomographNumber(String homographNumber) {
    this.homographNumber = homographNumber;
  }

  public ThesaurusEntry senses(List<ThesaurusSense> senses) {
    this.senses = senses;
    return this;
  }

  public ThesaurusEntry addSensesItem(ThesaurusSense sensesItem) {
    this.senses.add(sensesItem);
    return this;
  }

   /**
   * Complete list of senses
   * @return senses
  **/
  public List<ThesaurusSense> getSenses() {
    return senses;
  }

  public void setSenses(List<ThesaurusSense> senses) {
    this.senses = senses;
  }

  public ThesaurusEntry variantForms(VariantFormsList variantForms) {
    this.variantForms = variantForms;
    return this;
  }

   /**
   * Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
   * @return variantForms
  **/
  public VariantFormsList getVariantForms() {
    return variantForms;
  }

  public void setVariantForms(VariantFormsList variantForms) {
    this.variantForms = variantForms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThesaurusEntry thesaurusEntry = (ThesaurusEntry) o;
    return Objects.equals(this.homographNumber, thesaurusEntry.homographNumber) &&
        Objects.equals(this.senses, thesaurusEntry.senses) &&
        Objects.equals(this.variantForms, thesaurusEntry.variantForms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(homographNumber, senses, variantForms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThesaurusEntry {\n");
    
    sb.append("    homographNumber: ").append(toIndentedString(homographNumber)).append("\n");
    sb.append("    senses: ").append(toIndentedString(senses)).append("\n");
    sb.append("    variantForms: ").append(toIndentedString(variantForms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

