/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gatebuzz.oxfordapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;


/**
 * Schema for lexicalcategories, registers utility endpoints.
 */
public class UtilityLabels   {
  @SerializedName("metadata")
  private Object metadata = null;

  @SerializedName("results")
  private Map<String, UtilityLabelsResults> results = new HashMap<String, UtilityLabelsResults>();

  public UtilityLabels metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Additional Information provided by OUP
   * @return metadata
  **/
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public UtilityLabels results(Map<String, UtilityLabelsResults> results) {
    this.results = results;
    return this;
  }

  public UtilityLabels putResultsItem(String key, UtilityLabelsResults resultsItem) {
    this.results.put(key, resultsItem);
    return this;
  }

   /**
   * Mapping of labels available.
   * @return results
  **/
  public Map<String, UtilityLabelsResults> getResults() {
    return results;
  }

  public void setResults(Map<String, UtilityLabelsResults> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UtilityLabels utilityLabels = (UtilityLabels) o;
    return Objects.equals(this.metadata, utilityLabels.metadata) &&
        Objects.equals(this.results, utilityLabels.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UtilityLabels {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

